openapi: 3.0.3
info:
  title: Room Tempetature Measurement API
  version: 1.0.0
  description: 室内環境計測・通知システムのAPI仕様書
servers:
  - url: http://localhost:3000/api
security: []
paths:
  /notification:
    $ref: "./paths/notification.yaml"
  /status:
    $ref: "./paths/status.yaml"
  /setting:
    $ref: "./paths/setting.yaml"
  /current/{device_id}:
    $ref: "./paths/current_{device_id}.yaml"
  /history/inside/{device_id}/{period}:
    $ref: "./paths/history_inside_{device_id}_{period}.yaml"
  /history/outside/{device_id}/{period}:
    $ref: "./paths/history_outside_{device_id}_{period}.yaml"
  /threshold/{device_id}:
    $ref: "./paths/threshold_{device_id}.yaml"
