openapi: 3.0.3

info:
  title: Room Tempetature Measurement API
  version: 1.0.0
  description: 室内環境計測・通知システムのAPI仕様書
servers:
  - url: http://localhost:3000/api

paths:
  /notification:
    $ref: "./paths/notification.yaml"
                  
components:
  schemas:
    SampleRequest:
      type: object
      properties:
        id:
          type: integer
          format: int32
          example: 10
          description: ID
        hoge:
          type: string
          example: "sample"
          description: hoge
